services:
  db:
    image: mysql:8.0
    container_name: laravel_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hellocse
    networks:
      - laravel
    volumes:
      - db_data:/var/lib/mysql
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hellocsetest_app
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=hellocse
      - DB_USERNAME=root
      - DB_PASSWORD=root
    depends_on:
      - db
    networks:
      - laravel


networks:
  laravel:
    driver: bridge

volumes:
  db_data:
